### ISSUE TITLE
[1.14] Crashes on launch (AbstractMethodError)

### ISSUE THREAD

**Issue by Renari** [tterrag1098/Blur#41]
Crash report:
```
---- Minecraft Crash Report ----
// Don't do that.

Time: 3/14/20 10:44 PM
Description: Rendering overlay

java.lang.AbstractMethodError: Method com/tterrag/blur/util/ShaderResourcePack.func_195758_a(Lnet/minecraft/resources/ResourcePackType;Ljava/lang/String;ILjava/util/function/Predicate;)Ljava/util/Collection; is abstract
	at com.tterrag.blur.util.ShaderResourcePack.func_195758_a(ShaderResourcePack.java) ~[?:1.1.0-1] {re:classloading}
	at net.minecraft.resources.FallbackResourceManager.func_199003_a(FallbackResourceManager.java:112) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.resources.SimpleReloadableResourceManager.func_199003_a(SimpleReloadableResourceManager.java:82) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.gui.fonts.FontResourceManager$1.func_212854_a_(SourceFile:63) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.fonts.FontResourceManager$1.func_212854_a_(SourceFile:55) ~[?:?] {re:classloading}
	at net.minecraft.client.resources.ReloadListener.func_215270_b(SourceFile:11) ~[?:?] {re:classloading}
	at net.minecraft.client.resources.ReloadListener$$Lambda$3195/128918182.get(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1574) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:544)

-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.ResourceLoadProgressGui
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:544)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:890)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$414/2144659477.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1032418528 bytes (984 MB) / 3189768192 bytes (3042 MB) up to 7635730432 bytes (7282 MB)
	CPUs: 16
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8192m -Xms256m -XX:PermSize=256m
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.2.3.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.3.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.5-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.2.3.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.3.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.2.3.jar fml TRANSFORMATIONSERVICE 
	FML: 28.2
	Forge: net.minecraftforge:28.2.3
	FML Language Providers: 
		javafml@28.2
		minecraft@1
	Mod List: 
		CraftPresence-1.14.4-1.6.1.jar CraftPresence {craftpresence@property(class java.lang.String, provider(?)) CREATE_REGISTRIES}
		blockdrops-1.14.4-1.0.2.jar Block Drops {blockdrops@1.0.2 CREATE_REGISTRIES}
		justenoughbeacons-1.2.jar Just Enough Beacons {justenoughbeacons@1.2 CREATE_REGISTRIES}
		TrashSlot_1.14.4-10.4.8.jar TrashSlot {trashslot@10.4.8 CREATE_REGISTRIES}
		mining-helmet-1.14.4-1.0.7.jar Mining Helmet {mining_helmet@1.0.7 CREATE_REGISTRIES}
		jei-1.14.4-6.0.0.27.jar Just Enough Items {jei@6.0.0.27 CREATE_REGISTRIES}
		JustEnoughCalculation-1.14.4-3.4.2.jar Just Enough Calculation {jecalculation@3.4.2 CREATE_REGISTRIES}
		AttributeFix-1.14.4-3.0.3.jar AttributeFix {attributefix@3.0.3 CREATE_REGISTRIES}
		bambooeverything-1.14-1.5.0.jar Bamboo Everything {bambooeverything@1.14-1.5.0 CREATE_REGISTRIES}
		modnametooltip_1.14.3-1.12.1.jar Mod Name Tooltip {modnametooltip@1.12.1 CREATE_REGISTRIES}
		KleeSlabs_1.14.4-7.4.8.jar KleeSlabs {kleeslabs@7.4.8 CREATE_REGISTRIES}
		invtweaks-1.14.4-1.0.2.jar Inventory Tweaks Reborn {invtweaks@1.14.4-1.0.2 CREATE_REGISTRIES}
		LightOverlay-3.6.2.jar Light Overlay Forge {lightoverlay-forge@3.6.2 CREATE_REGISTRIES}
		Controlling-5.0.6.jar Controlling {controlling@5.0.6 CREATE_REGISTRIES}
		ReAuth-1.14-3.8.0.jar ReAuth {reauth@3.8.0 CREATE_REGISTRIES}
		Placebo-1.14.4-2.3.5.jar Placebo {placebo@2.3.5 CREATE_REGISTRIES}
		SereneSeasons-1.14.4-2.0.0.40-universal.jar Serene Seasons {sereneseasons@1.14.4-2.0.0.40 CREATE_REGISTRIES}
		VanillaTweaks-1.14.4.1.5.12.jar VanillaTweaks {vanillatweaks@1.14.4.1.5.12 CREATE_REGISTRIES}
		WitherSkeletonTweaks-1.14.4-3.1.0.jar Wither Skeleton Tweaks {wstweaks@3.1.0 CREATE_REGISTRIES}
		randompatches-1.14.4-1.21.0.0.jar RandomPatches {randompatches@1.14.4-1.21.0.0 CREATE_REGISTRIES}
		fragiletorches-1.14.4-1.0.0.jar fragiletorches Mod {fragiletorches@1.14.4-1.0.0 CREATE_REGISTRIES}
		Morpheus-1.14.4-4.2.44.jar Morpheus {morpheus@version CREATE_REGISTRIES}
		deathquotes-1.2-1.14.4.jar DeathQuotes {deathquotes@1.0 CREATE_REGISTRIES}
		SnowRealMagic-1.14.4-1.5.2.jar Snow! Real Magic! {snowrealmagic@1.5.2 CREATE_REGISTRIES}
		Kiwi-1.14.4-2.6.3.jar Kiwi {kiwi@2.6.3 ERROR}
		PackingTape-1.14.4-0.9.2.jar Packing Tape {packingtape@0.9.2 CREATE_REGISTRIES}
		colorfulhealthbar-2.0.0.jar Colorful Health Bar {colorfulhealthbar@2.0.0 CREATE_REGISTRIES}
		JustEnoughResources-1.14.4-0.10.1.74.jar Just Enough Resources {jeresources@0.10.1.74 CREATE_REGISTRIES}
		immersive-portals-0.15(for mc 1.14 with forge).jar Immersive Portals {immersive_portals@0.15 CREATE_REGISTRIES}
		CraftTweaker-1.14.4-5.0.1.133.jar CraftTweaker {crafttweaker@5.0.1.133 CREATE_REGISTRIES}
		forge-1.14.4-28.2.3-universal.jar Forge {forge@28.2.3 CREATE_REGISTRIES}
		shetiphiancore-1.14-3.6.1.jar ShetiPhian-Core {shetiphiancore@3.6.1 CREATE_REGISTRIES}
		corail_pillar_extension_quark-4.0.0-1.14.4.jar Corail Pillar - Quark & Botania Extension {corail_pillar_extension_quark@4.0.0 CREATE_REGISTRIES}
		CraftingTweaks_1.14.4-10.2.1.jar Crafting Tweaks {craftingtweaks@10.2.1 CREATE_REGISTRIES}
		forge-1.14.4-28.2.3-client.jar Minecraft {minecraft@1.14.4 CREATE_REGISTRIES}
		swingthroughgrass-1.14.4-1.3.2.jar SwingThroughGrass {swingthroughgrass@1.14.4-1.3.2 CREATE_REGISTRIES}
		AmbientSounds_v3.0.16_mc1.14.4.jar Ambient Sounds {ambientsounds@3.0.3 CREATE_REGISTRIES}
		MouseTweaks-2.13-mc1.14.4.jar Mouse Tweaks {mousetweaks@2.13 CREATE_REGISTRIES}
		Ping-1.14.4-1.6.3.jar Ping {ping@1.14.4-1.6.3 CREATE_REGISTRIES}
		Blur-1.1.0-1.jar Blur {blur@1.1.0-1 ERROR}
		curios-FORGE-1.14.4-1.0.6.1.jar Curios API {curios@FORGE-1.14.4-1.0.6.1 CREATE_REGISTRIES}
		AutoRegLib-1.4-35.jar AutoRegLib {arl@1.4-35 CREATE_REGISTRIES}
		Quark-r2.0-212.jar Quark {quark@r2.0-212 CREATE_REGISTRIES}
		FastWorkbench-1.14.4-2.1.4.jar FastWorkbench {fastbench@2.1.4 CREATE_REGISTRIES}
		ClothConfig2-1.4.1.jar Cloth Config Forge v2 API {cloth-config2@1.4.1 CREATE_REGISTRIES}
		multibeds-1.14-1.5.2.jar Multi-Beds {multibeds@1.5.0 CREATE_REGISTRIES}
		ScreenshotToClipboard-1.14.4-1.0.3.jar Screenshot to Clipboard {screenshotclipboard@1.14.4-1.0.3 CREATE_REGISTRIES}
		noRecipeBook_v1.4.1formc1.14.4.jar No Recipe Book {norecipebook@1.4.1 CREATE_REGISTRIES}
		FastFurnace-1.14.4-2.2.4.jar FastFurnace {fastfurnace@2.2.4 CREATE_REGISTRIES}
		World-Stripper-1.7.2-1.14.4.jar World Stripper {worldstripper@version CREATE_REGISTRIES}
		AppleSkin-mc1.14.4-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 CREATE_REGISTRIES}
		AI-Improvements-1.14.4-0.3.0.jar AI-Improvements {aiimprovements@0.2.2 CREATE_REGISTRIES}
		Login_Shield-1.14-17-g7625bc0.jar Login Shield {login_shield@1.14-17-g7625bc0 CREATE_REGISTRIES}
		solcarrot-1.14.4-1.9.4.jar Spice of Life: Carrot Edition {solcarrot@1.14.4-1.9.4 CREATE_REGISTRIES}
		Charm-1.14.4-1.5.2.jar Charm {charm@1.14.4-1.5.2 CREATE_REGISTRIES}
		bwncr-1.14.4-3.5.12.jar Bad Wither No Cookie Reloaded {bwncr@1.14.4-3.5.12 CREATE_REGISTRIES}
		FastLeafDecay-v17.jar FastLeafDecay {fastleafdecay@v17 CREATE_REGISTRIES}
		CosmeticArmorReworked-1.14.4-v1b.jar CosmeticArmorReworked {cosmeticarmorreworked@1.14.4-v1b CREATE_REGISTRIES}
		SoundFilters-0.13_for_1.14.4.jar Sound Filters {soundfilters@0.13_for_1.14.4 CREATE_REGISTRIES}
		ServerTabInfo-1.14.4-1.2.6.jar Server Tab Info {servertabinfo@1.2.6 CREATE_REGISTRIES}
		overloadedarmorbar-3.0.0b.jar Overloaded Armor Bar {overloadedarmorbar@3.0.0b CREATE_REGISTRIES}
		corail_pillar-4.6.0-1.14.4.jar Corail Pillar {corail_pillar@4.6.0 CREATE_REGISTRIES}
		DefaultOptions_1.14.4-10.2.7.jar Default Options {defaultoptions@10.2.7 CREATE_REGISTRIES}
		BetterAdvancements-1.14.4-0.1.0.90.jar Better Advancements {betteradvancements@0.1.0.90 CREATE_REGISTRIES}
	Launched Version: forge-28.2.3
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce RTX 2060 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 442.50, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 16x Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
```

Twitch launcher instance:
[Phuzed Sekai 1.14-0.0.1.zip](https://github.com/tterrag1098/Blur/files/4333728/Phuzed.Sekai.1.14-0.0.1.zip)

**Comment by tterrag1098** [comment]
The latest update only works on 1.15.x, it's incorrectly marked on CurseForge.
